//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountLogInTable
    {
        public int AccountLogId { get; set; }
        public string AccountLogName { get; set; }
        public string AccountLogPassword { get; set; }
		public string RestName { get; internal set; }
	}
}
