//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectRequestTable
    {
        public int CollectRequestId { get; set; }
        public string CollectStatus { get; set; }
        public int RestId { get; set; }
        public int EmpId { get; set; }
        public string PlacingTime { get; set; }
    
        public virtual EmpTable EmpTable { get; set; }
        public virtual FoodTable FoodTable { get; set; }
        public virtual RestaurantTable RestaurantTable { get; set; }
    }
}
