//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTable
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpLocation { get; set; }
        public string RequestsCompleted { get; set; }
        public int NGOId { get; set; }
    
        public virtual CollectRequestTable CollectRequestTable { get; set; }
        public virtual NGOTable NGOTable { get; set; }
    }
}
