//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodTable
    {
        public int FdID { get; set; }
        public string FdName { get; set; }
        public string FdAmount { get; set; }
        public string CollectRequestId { get; set; }
    
        public virtual CollectRequestTable CollectRequestTable { get; set; }
    }
}
