//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZeroHungerEntities : DbContext
    {
        public ZeroHungerEntities()
            : base("name=ZeroHungerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountLogInTable> AccountLogInTables { get; set; }
        public virtual DbSet<CollectRequestTable> CollectRequestTables { get; set; }
        public virtual DbSet<EmpTable> EmpTables { get; set; }
        public virtual DbSet<FoodTable> FoodTables { get; set; }
        public virtual DbSet<NGOTable> NGOTables { get; set; }
        public virtual DbSet<RestaurantTable> RestaurantTables { get; set; }
    }
}
